<script src="{{ asset('template1/js/jquery.min.js') }}"></script>
<script src="{{ asset('template1/js/jquery.validate.min.js') }}"></script>
<script src="{{ asset('template1/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('template1/js/jquery.nice-select.min.js') }}"></script>
<script src="{{ asset('template1/js/jquery.nicescroll.min.js') }}"></script>
<script src="{{ asset('template1/js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('template1/js/jquery.countdown.min.js') }}"></script>
<script src="{{ asset('template1/js/jquery.slicknav.js') }}"></script>
<script src="{{ asset('template1/js/mixitup.min.js') }}"></script>
<script src="{{ asset('template1/js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('template1/js/main.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
